-- Modelo de datos PostgreSQL para SICA - E13-HU01
-- Debe ejecutarse dentro de una base de datos PostgreSQL ya creada.

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT chk_roles_nombre CHECK (btrim(nombre) <> '')
);

CREATE TABLE permisos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT chk_permisos_nombre CHECK (btrim(nombre) <> '')
);

-- Tabla intermedia que resuelve la relacion muchos a muchos.
CREATE TABLE rol_permiso (
    rol_id BIGINT NOT NULL,
    permiso_id BIGINT NOT NULL,
    PRIMARY KEY (rol_id, permiso_id),
    CONSTRAINT fk_rol_permiso_rol
        FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_rol_permiso_permiso
        FOREIGN KEY (permiso_id) REFERENCES permisos(id) ON DELETE CASCADE
);

CREATE TABLE empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    identificador VARCHAR(30) NOT NULL UNIQUE,
    CONSTRAINT chk_empresas_nombre CHECK (btrim(nombre) <> ''),
    CONSTRAINT chk_empresas_identificador CHECK (btrim(identificador) <> '')
);

CREATE TABLE personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    documento VARCHAR(30) NOT NULL UNIQUE,
    tipo VARCHAR(20) NOT NULL,
    empresa_id BIGINT,
    foto_url VARCHAR(255),
    estado_acceso VARCHAR(20) NOT NULL DEFAULT 'HABILITADO',
    CONSTRAINT chk_personas_nombre CHECK (btrim(nombre) <> ''),
    CONSTRAINT chk_personas_documento CHECK (btrim(documento) <> ''),
    CONSTRAINT chk_personas_tipo CHECK (tipo IN ('TRABAJADOR', 'INVITADO')),
    CONSTRAINT chk_personas_estado_acceso
        CHECK (estado_acceso IN ('HABILITADO', 'RESTRINGIDO')),
    CONSTRAINT chk_personas_empresa
        CHECK (tipo = 'TRABAJADOR' OR empresa_id IS NULL),
    CONSTRAINT fk_personas_empresa
        FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE RESTRICT
);

-- Los datos personales se almacenan solo en personas. El usuario contiene
-- exclusivamente las credenciales y su relacion de acceso al sistema.
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id BIGINT NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol_id BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_usuarios_username CHECK (btrim(username) <> ''),
    CONSTRAINT chk_usuarios_password CHECK (btrim(password) <> ''),
    CONSTRAINT fk_usuarios_persona
        FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_usuarios_rol
        FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE RESTRICT
);

CREATE TABLE visitas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invitado_id BIGINT NOT NULL,
    persona_visitada_id BIGINT NOT NULL,
    fecha_hora_visita TIMESTAMP WITH TIME ZONE NOT NULL,
    estado VARCHAR(40) NOT NULL,
    fecha_hora_checkin TIMESTAMP WITH TIME ZONE,
    usuario_checkin VARCHAR(50),
    fecha_hora_checkout TIMESTAMP WITH TIME ZONE,
    usuario_checkout VARCHAR(50),
    CONSTRAINT chk_visitas_personas_distintas
        CHECK (invitado_id <> persona_visitada_id),
    CONSTRAINT chk_visitas_estado CHECK (estado IN (
        'APROBADO', 'RECHAZADO', 'PENDIENTE_APROBACION',
        'PENDIENTE_APROBACION_POR_OLVIDO', 'DENTRO',
        'FINALIZADA', 'CERRADA_POR_SISTEMA'
    )),
    CONSTRAINT chk_visitas_checkout_posterior
        CHECK (fecha_hora_checkout IS NULL
            OR fecha_hora_checkin IS NULL
            OR fecha_hora_checkout >= fecha_hora_checkin),
    CONSTRAINT fk_visitas_invitado
        FOREIGN KEY (invitado_id) REFERENCES personas(id) ON DELETE RESTRICT,
    CONSTRAINT fk_visitas_persona_visitada
        FOREIGN KEY (persona_visitada_id) REFERENCES personas(id) ON DELETE RESTRICT
);

CREATE TABLE incidentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(500) NOT NULL,
    fecha_hora TIMESTAMP WITH TIME ZONE NOT NULL,
    persona_id BIGINT,
    usuario_responsable VARCHAR(50) NOT NULL,
    CONSTRAINT chk_incidentes_descripcion CHECK (btrim(descripcion) <> ''),
    CONSTRAINT chk_incidentes_usuario CHECK (btrim(usuario_responsable) <> ''),
    CONSTRAINT fk_incidentes_persona
        FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE SET NULL
);

CREATE TABLE bitacora_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accion VARCHAR(50) NOT NULL,
    entidad VARCHAR(30) NOT NULL DEFAULT 'SISTEMA',
    descripcion VARCHAR(255) NOT NULL,
    usuario_responsable VARCHAR(50) NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resultado VARCHAR(20) NOT NULL DEFAULT 'EXITOSO',
    CONSTRAINT chk_bitacora_accion CHECK (btrim(accion) <> ''),
    CONSTRAINT chk_bitacora_entidad CHECK (btrim(entidad) <> ''),
    CONSTRAINT chk_bitacora_descripcion CHECK (btrim(descripcion) <> ''),
    CONSTRAINT chk_bitacora_usuario CHECK (btrim(usuario_responsable) <> ''),
    CONSTRAINT chk_bitacora_resultado CHECK (resultado IN ('EXITOSO', 'FALLIDO'))
);

CREATE INDEX idx_visitas_invitado_fecha
    ON visitas (invitado_id, fecha_hora_visita DESC);
CREATE INDEX idx_visitas_persona_visitada_estado
    ON visitas (persona_visitada_id, estado);
CREATE INDEX idx_visitas_estado ON visitas (estado);
CREATE INDEX idx_incidentes_persona ON incidentes (persona_id);
CREATE INDEX idx_bitacora_fecha ON bitacora_auditoria (fecha DESC);

-- Mantiene la bitacora inmutable tambien en PostgreSQL.
CREATE OR REPLACE FUNCTION impedir_cambio_bitacora()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'Los registros de auditoria no se pueden modificar ni eliminar';
END;
$$;

CREATE TRIGGER bloquear_actualizacion_bitacora
BEFORE UPDATE ON bitacora_auditoria
FOR EACH ROW
EXECUTE FUNCTION impedir_cambio_bitacora();

CREATE TRIGGER bloquear_eliminacion_bitacora
BEFORE DELETE ON bitacora_auditoria
FOR EACH ROW
EXECUTE FUNCTION impedir_cambio_bitacora();
